name: "Deploy Taskr"

on:
  push:
    tags:
      - '*'

env:
  PROJECT_PATH: "ProjectManagement.Presentation.WPF/ProjectManagement.Presentation.WPF.csproj"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}
  
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore -p:PublishSingleFile=true
  
      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -p:PublishSingleFile=true --no-build
  
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Add assets to release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: ProjectManagement.Presentation.WPF/bin/Release/net6.0-windows/win-x64/publish/*
          release-url: ${{ steps.create_release.output.upload_url }}